version: '3'

services:

    app:
        build: .
        container_name: warehouse-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
            - "3000:3000"
            - "35729:35729"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: warehouse-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        command: --innodb-use-native-aio=0
        container_name: warehouse-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=warehouse-test
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
