FROM php:7.3.6-fpm-alpine3.10

RUN apk add --no-cache shadow openssl bash mysql-client nodejs npm git
# Install php extensions
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-configure pdo_mysql

WORKDIR /var/www

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www

RUN usermod -u 1000 www-data

RUN ln -s public html

USER www-data

EXPOSE 9000

ENTRYPOINT [ "php-fpm" ]
